/* Generated By:JavaCC: Do not edit this line. SimpleExprParserConstants.java */
package com.jjtx.exprs;
/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface SimpleExprParserConstants {
    /**
     * End of File.
     */
    int EOF = 0;

    /**
     * RegularExpression Id.
     */
    int PLUS = 1;

    /**
     * RegularExpression Id.
     */
    int MINUS = 2;

    /**
     * RegularExpression Id.
     */
    int NULL = 3;

    /**
     * RegularExpression Id.
     */
    int INTEGER = 4;

    /**
     * RegularExpression Id.
     */
    int DIGITS = 5;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = new String[]{ "<EOF>", "\"+\"", "\"-\"", "\"null\"", "<INTEGER>", "<DIGITS>", "\"(\"", "\")\"" };
}
