/*
 * Generated by JJTricks at Thu Jan 01 01:00:00 CET 1970
 * Not intended for manual editing.
 */
package com.jjtx.exprs;
public interface SimpleExprParserTreeConstants {
  public int JJTASTNODE = 0;
  public int JJTPARENTHESIZEDEXPR = 1;
  public int JJTINTEGERLITERAL = 2;
  public int JJTBINARYEXPR = 3;
  public int JJTNULLLITERAL = 4;
  public String[] jjtNodeName = {
    "ASTNode", "ParenthesizedExpr", "IntegerLiteral", "BinaryExpr", "NullLiteral",
  };
}