/*
 * Generated by JJTricks at Thu Jan 01 01:00:00 CET 1970
 * Not intended for manual editing.
 */
package com.jjtx.exprs;
public interface SimpleExprParserTreeConstants {
  public int JJTASTNODE = 0;
  public int JJTASTPARENTHESIZEDEXPR = 1;
  public int JJTASTINTEGERLITERAL = 2;
  public int JJTASTBINARYEXPR = 3;
  public int JJTASTNULLLITERAL = 4;
  public String[] jjtNodeName = {
    "ASTNode", "ASTParenthesizedExpr", "ASTIntegerLiteral", "ASTBinaryExpr", "ASTNullLiteral",
  };
}