/*
 * Generated by JJTricks at Thu Jan 01 01:00:00 CET 1970
 * Not intended for manual editing.
 */

package com.jjtx.exprs;

public interface SimpleExprParserTreeConstants {

  public int JJTASTNODE = 0;
  public int JJTBINARYEXPR = 1;
  public int JJTINTEGERLITERAL = 2;
  public int JJTNULLLITERAL = 3;
  public int JJTPARENTHESIZEDEXPR = 4;

  public String[] jjtNodeName = {
    "ASTNode", "BinaryExpr", "IntegerLiteral", "NullLiteral", "ParenthesizedExpr",
  };
}