package com.github.oowekyala.jjtx.postprocessor

import com.github.oowekyala.ijcc.lang.model.IGrammarOptions
import com.github.oowekyala.ijcc.lang.model.addNodePackage
import com.github.oowekyala.ijcc.lang.model.addParserPackage
import com.github.oowekyala.ijcc.lang.model.parserSimpleName
import com.github.oowekyala.jjtx.JjtxContext
import com.github.oowekyala.jjtx.JjtxOptsModel
import com.github.oowekyala.jjtx.templates.vbeans.ClassVBean


val JjtxContext.tokenClass: ClassVBean
    get() = SpecialTemplate.TOKEN.actualLocation(this.jjtxOptsModel)

/**
 * Special templates are the support files necessary for the parser to function.
 *
 * They are either generated by JavaCC, or by JJTricks. Configuration works the
 * same regardless of the way they're generated.
 */
enum class SpecialTemplate(val id: String, private val defaultClassSimpleName: String = id.capitalize()) {

    // Those are all generated by JavaCC, but can be replaced

    TOKEN("token"),
    TOKEN_MANAGER("tokenManager"),
    CHAR_STREAM("charStream"),
    /**
     * IDs of tokens, images of string tokens.
     */
    TOKEN_IDS("tokenIds") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            ClassVBean(opts.addParserPackage(opts.parserSimpleName + "Constants"))
    },
    // This one is added by jjtricks
    TOKEN_FACTORY("tokenFactory"),


    LEX_EXCEPTION("lexException"),
    PARSE_EXCEPTION("parseException"),

    // special templates relevant to tree building
    // Those are generated by VTL templating

    JJ_FILE("jjFile") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            throw UnsupportedOperationException("JJ File special template has no default location")
    },

    TREE_BUILDER("treeBuilder") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            ClassVBean(opts.addNodePackage("JJT" + opts.parserSimpleName + "State"))
    },
    NODE_MANIPULATOR("manipulator") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            ClassVBean(opts.addNodePackage("NodeManipulator"))
    },
    NODE_FACTORY("nodeFactory") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            ClassVBean(opts.addNodePackage(opts.grammarName.orEmpty().capitalize() + "NodeFactory"))
    },
    NODE_IDS("nodeIds") {
        override fun defaultLocation(opts: IGrammarOptions): ClassVBean =
            ClassVBean(opts.addNodePackage(opts.parserSimpleName + "TreeConstants"))
    },
    ;


    fun actualLocation(opts: IGrammarOptions): ClassVBean =
        (opts as? JjtxOptsModel)?.javaccGen?.supportFiles?.get(id)?.genFqcn?.let(::ClassVBean)
            ?: defaultLocation(opts)

    open fun defaultLocation(opts: IGrammarOptions) =
        ClassVBean(opts.addParserPackage(defaultClassSimpleName))


    companion object {

        fun findById(id: String): SpecialTemplate? = values().firstOrNull { it.id == id }

    }


}
