/* Generated by JJTricks on Thu Jan 01 01:00:00 CET 1970 -- Not intended for manual editing. */

package com.jjtx.exprs;

import com.jjtx.exprs.Token;

import com.jjtx.exprs.ASTNode;
import com.jjtx.exprs.JJTSimpleExprParserState;
import com.jjtx.exprs.NodeManipulator;
import com.jjtx.exprs.SimpleExprParserTreeConstants;
import com.jjtx.exprs.SimpleExprsNodeFactory;

import com.jjtx.exprs.SimpleExprParser;

/**
 * This class is responsible for creating new nodes from their ID. The construction method is called
 * by the parser each time a node scope is opened.
 */
final class SimpleExprsNodeFactory {

  private SimpleExprsNodeFactory() {
    // static class
  }

  public static ASTNode createNode(int id) {
    switch (id) {
      case SimpleExprParserTreeConstants.JJTPARENTHESIZEDEXPR:
        return new ASTParenthesizedExpr(id);
      case SimpleExprParserTreeConstants.JJTINTEGERLITERAL:
        return new ASTIntegerLiteral(id);
      case SimpleExprParserTreeConstants.JJTBINARYEXPR:
        return new ASTBinaryExpr(id);
      case SimpleExprParserTreeConstants.JJTNULLLITERAL:
        return new ASTNullLiteral(id);
      case SimpleExprParserTreeConstants.JJTASTNODE:
        // JJTricks doesn't know whether it's an interface or anything...
        // The parser will never attempt to create nodes with those IDs though.
        throw new IllegalArgumentException(
            "Node "
                + id
                + " doesn't correspond to a production and can't be built by this default factory");
      default:
        throw new IllegalArgumentException("Unknown node id " + id);
    }
  }
}
