/* Generated by JJTricks on Thu Jan 01 01:00:00 CET 1970 -- Not intended for manual editing. */

package org.exprs.ast;

import org.exprs.ast.DummyExprParserTreeConstants;
import org.javacc.jjtree.DummyExprParser;

public abstract class AbstractMyNodeParent implements MyNodeParent {

  private final int id;
  private final DummyExprParser parser;

  // TODO handle children

  public AbstractMyNodeParent(int id) {
    this(null, id);
  }

  public AbstractMyNodeParent(DummyExprParser parser, int id) {
    this.id = id;
    this.parser = parser;
  }

  @Override
  public String toString() {
    return DummyExprParserTreeConstants.jjtNodeName[id];
  }

  @Override
  public <T> void jjtAccept(DummyExprVisitorX<T> visitor, T data) {
    visitor.visit(this, data);
  }
}