/* Generated by JJTricks on Thu Jan 01 01:00:00 CET 1970 -- Not intended for manual editing. */

package org.exprs.ast;
/** Root node for the DummyExpr AST. */
public interface MyNodeParent {
  // TODO
}