/*
 * Generated by JJTricks at Thu Jan 01 01:00:00 CET 1970
 * Not intended for manual editing.
 */
package com.exprs.ast;
public interface SimpleExprParserTreeConstants {
  public int JJTMYNODEPARENT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTLITERAL = 2;
  public int JJTNULLLITERAL = 3;
  public int JJTINTEGERLITERAL = 4;
  public int JJTPARENTHESIZEDEXPR = 5;
  public int JJTBINARYEXPR = 6;
  public String[] jjtNodeName = {
    "MyNodeParent",
    "Expression",
    "Literal",
    "NullLiteral",
    "IntegerLiteral",
    "ParenthesizedExpr",
    "BinaryExpr",
  };
}