/*
 * Generated by JJTricks at Thu Jan 01 01:00:00 CET 1970
 * Not intended for manual editing.
 */

package com.exprs.ast;

public interface SimpleExprParserTreeConstants {

  public int JJTBINARYEXPR = 0;
  public int JJTEXPRESSION = 1;
  public int JJTINTEGERLITERAL = 2;
  public int JJTLITERAL = 3;
  public int JJTMYNODEPARENT = 4;
  public int JJTNULLLITERAL = 5;
  public int JJTPARENTHESIZEDEXPR = 6;

  public String[] jjtNodeName = {
    "BinaryExpr",
    "Expression",
    "IntegerLiteral",
    "Literal",
    "MyNodeParent",
    "NullLiteral",
    "ParenthesizedExpr",
  };
}