PARSER_BEGIN(JJTreeParser)

PARSER_END(JJTreeParser)



void test1() #OptionBinding :
{}
{
  "ff" // an expansion unit
}

void test2() #OptionBinding :
{}
{
  "ff" "cd" // two expansion units in a sequence
}

void test2() #OptionBinding :
{}
{
  "ff" | "cd" // each expansion unit is in a sequence, the alternative encloses the two
}

void test2() #OptionBinding :
{}
{
  "ff" | "cd" | "f" "c" // same but check that the node is not left recursive
}

void test2() #OptionBinding :
{}
{
  "ff" | "cd" | "f" "c"
}

