<fold text='/PARSER DECLARATION/' expand='false'>PARSER_BEGIN(JJTreeParser)
PARSER_END(JJTreeParser)</fold>

<fold text='SKIP: {..}' expand='false'>SKIP : {
    "(:" <fold text="{..}">{ commentNestingDepth++; }</fold>
}


<fold text='/BNF QuantifiedExpr()/' expand='true'>void QuantifiedExpr():
{}
{
  (<SOME> <fold text='{..}' expand='false'>{ jjtThis.setUniversallyQuantified(false); }</fold>)
  VarBindingList(false)
  <SATISFIES> ExprSingle()
}</fold>

<fold text='/JAVACODE node_descriptor_expression() #NodeDescriptorExpression/' expand='true'>JAVACODE
void node_descriptor_expression() #NodeDescriptorExpression
{
  Token tok;
  int nesting = 1;
  while (true) {
    tok = getToken(1);
    if (tok.kind == 0) {
      throw new ParseException();
    }
    if (tok.kind == LPAREN) nesting++;
    if (tok.kind == RPAREN) {
      nesting--;
      if (nesting == 0) break;
    }
    tok = getNextToken();
  }
}</fold>
