PARSER_BEGIN(JJTreeParser)

    package org.javacc.jjtree;
    /**
     *  This is my parser declaration
     */
    public class JJTreeParser {

    }

PARSER_END(JJTreeParser)



void emptyAlt(List<Foo> generic): {}
{
    "f"
}

Frab emptyAlt2(List<Foo> generic): {}
{
    "f"
}

Frab<Foo> emptyAlt9(List<Foo> generic): {}
{
    "f"
}

Frab<? extends Bar> emptyAlt3(List<Foo>... generic): {}
{
    "f"
}

Frab<?> emptyAlt4(List<Foo>... generic): {}
{
    "f"
}

Frab<?>[] emptyAlt5(List<Foo>... generic): {}
{
    "f"
}

Frab<?>[] emptyAlt6(List<Foo>[] generic): {}
{
    "f"
}

Frab<?>[] emptyAlt7(List<int[]>[] generic): {}
{
    "f"
}
Frab<?>[] emptyAlt8(List<int>[] generic): {}
{
    "f"
}
