PARSER_BEGIN(JJTreeParser)

    package org.javacc.jjtree;
    /**
     *  This is my parser declaration
     */
    public class JJTreeParser {

    }

PARSER_END(JJTreeParser)



void lookaheads(): {}
{
    LOOKAHEAD(1, ID(), {getToken(1).kind != NATURAL})       // lexical, syntactic, semantic
    LOOKAHEAD({getToken(1).kind != NATURAL})                // semantic, not syntactic
    LOOKAHEAD(1)                                            // lexical
    LOOKAHEAD(TableAlias(), {getToken(1).kind != NATURAL})  // syntactic, semantic
    LOOKAHEAD(1, ("foo" | "bar") )                          // lexical, syntactic

    LOOKAHEAD({ doSth(); }, {getToken(1).kind != NATURAL})  // invalid parse

    "f" <f> | "fk" // FIXME shouldn't be affected
}

// shouldn't be affected by the failed lookahead above
void foo(): {} {
    "a" | "b"
}