options {
    // MULTI = true;
}

PARSER_BEGIN(SimpleExprParser)

    package com.jjtx.exprs;
    import org.exprs.ast.*;
    import org.exprs.ast.SimpleExprParserTreeConstants;
    import org.exprs.ast.SimpleExprsNodeFactory;
    import static org.exprs.ast.SimpleExprParserTreeConstants.*;


    /**
     *  This is my parser declaration
     */
    public class SimpleExprParser extends Foo<B> implements A {/*@bgen(jjtree)*/
    protected final org.exprs.ast.JJTSimpleExprParserState jjtree = new org.exprs.ast.JJTSimpleExprParserState();/*@egen*/

    }

PARSER_END(SimpleExprParser)

// Some token declarations
<DEFAULT>
TOKEN :{
  < PLUS: "+" >
| < MINUS: "-" >
| < NULL: "null" >
| < INTEGER: ["+",  "-"] <DIGITS> >
| < #DIGITS: (["0"-"9"])+ >
}


void Expression() : {}
{
      BinaryExpression()
    | /*@bgen(jjtree) NullLiteral */
{
    ExNullLiteral nullLiteral = (ExNullLiteral) SimpleExprsNodeFactory.jjtCreate(JJTNULLLITERAL);
    boolean nullLiteralNeedsClose = true;
    jjtree.openNodeScope(nullLiteral, getToken(1));
} try {
    /*@egen*/<NULL>
    /*@bgen(jjtree)*/
} catch (Throwable nullLiteralException) {
    if (nullLiteralNeedsClose) {
        jjtree.closeNodeScope(nullLiteral, getToken(0), true);
        nullLiteralNeedsClose = false;
    } else {
        jjtree.popNode();
    }
    throw nullLiteralException;
} finally {
    if (nullLiteralNeedsClose) {
        jjtree.closeNodeScope(nullLiteral, getToken(0), true);
    }
}
/*@egen*/

}

void BinaryExpression(): {
    /*@bgen(jjtree) BinaryExpr */
    ExBinaryExpr binaryExpr = (ExBinaryExpr) SimpleExprsNodeFactory.jjtCreate(JJTBINARYEXPR);
    boolean binaryExprNeedsClose = true;
    jjtree.openNodeScope(binaryExpr, getToken(1));
    /*@egen*/
    
}
{
    /*@bgen(jjtree) BinaryExpr */
     try {
        /*@egen*/UnaryExpr() [ ( "+" | "-" ) UnaryExpr() ]
        /*@bgen(jjtree)*/
    } catch (Throwable binaryExprException) {
        if (binaryExprNeedsClose) {
            jjtree.closeNodeScope(binaryExpr, getToken(0), binaryExpr.foo());
            binaryExprNeedsClose = false;
        } else {
            jjtree.popNode();
        }
        throw binaryExprException;
    } finally {
        if (binaryExprNeedsClose) {
            jjtree.closeNodeScope(binaryExpr, getToken(0), binaryExpr.foo());
        }
    }
    /*@egen*/
}


void UnaryExpr() : {}
{
  /*@bgen(jjtree) ParenthesizedExpr */
{
    ExParenthesizedExpr parenthesizedExpr = (ExParenthesizedExpr) SimpleExprsNodeFactory.jjtCreate(JJTPARENTHESIZEDEXPR);
    boolean parenthesizedExprNeedsClose = true;
    jjtree.openNodeScope(parenthesizedExpr, getToken(1));
} try {
    /*@egen*/("(" Expression() ")")
    /*@bgen(jjtree)*/
} catch (Throwable parenthesizedExprException) {
    if (parenthesizedExprNeedsClose) {
        jjtree.closeNodeScope(parenthesizedExpr, getToken(0), parenthesizedExpr.numChildren() > 1);
        parenthesizedExprNeedsClose = false;
    } else {
        jjtree.popNode();
    }
    throw parenthesizedExprException;
} finally {
    if (parenthesizedExprNeedsClose) {
        jjtree.closeNodeScope(parenthesizedExpr, getToken(0), parenthesizedExpr.numChildren() > 1);
    }
}
/*@egen*/
 | Integer()
}

void Integer(): {
    /*@bgen(jjtree) IntegerLiteral */
    ExIntegerLiteral integerLiteral = (ExIntegerLiteral) SimpleExprsNodeFactory.jjtCreate(JJTINTEGERLITERAL);
    boolean integerLiteralNeedsClose = true;
    jjtree.openNodeScope(integerLiteral, getToken(1));
    /*@egen*/
    
}
{
    /*@bgen(jjtree) IntegerLiteral */
     try {
        /*@egen*/<INTEGER>
        /*@bgen(jjtree)*/
    } catch (Throwable integerLiteralException) {
        if (integerLiteralNeedsClose) {
            jjtree.closeNodeScope(integerLiteral, getToken(0), true);
            integerLiteralNeedsClose = false;
        } else {
            jjtree.popNode();
        }
        throw integerLiteralException;
    } finally {
        if (integerLiteralNeedsClose) {
            jjtree.closeNodeScope(integerLiteral, getToken(0), true);
        }
    }
    /*@egen*/
}
