name: Build & verify

on:
  push:

jobs:
  build:
    name: Build plugin, verify compatiblity against declared minimum support version of intellij.
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          

      - name: Build the plugin using Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildPlugin
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          ide-versions: |
            ideaIC:2021.1
            ideaIU:2021.1
            ideaIC:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
