name: Build & verify

on:
  push:

jobs:
  build:
    name: Build plugin, verify compatiblity against declared minimum support version of intellij.
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the plugin using Gradle
        uses: eskatos/gradle-command-action@v1
          with:
            arguments: buildPlugin

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          ide-versions: |
            ideaIC:2020.1
            ideaIU:2020.1
            ideaIC:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
