PARSER_BEGIN(JJTreeParser)

package org.javacc.jjtree;

public class JJTreeParser {

  void jjtreeOpenNodeScope(Node n) {
	((JJTreeNode)n).setFirstToken(getToken(1));
  }

}

PARSER_END(JJTreeParser)


TOKEN :
{
//  Options is no longer a reserved word (Issue 126)
//  < _OPTIONS: "options" >
  < _LOOKAHEAD: "LOOKAHEAD" >
| < _IGNORE_CASE: "IGNORE_CASE" >
| < _PARSER_BEGIN: "PARSER_BEGIN" >
| < _PARSER_END: "PARSER_END" >
| < _JAVACODE: "JAVACODE" >
| < _TOKEN: "TOKEN" >
| < _SPECIAL_TOKEN: "SPECIAL_TOKEN" >
| < _MORE: "MORE" >
| < _SKIP: "SKIP" >
| < _TOKEN_MGR_DECLS: "TOKEN_MGR_DECLS" >
| < _EOF: "EOF" >
}



void option_binding() #OptionBinding :
	{
	  Token o, v;
	}
{
  ( o=<IDENTIFIER> | o="LOOKAHEAD" | o="IGNORE_CASE" | o="static" )
  "="
  (
     v=IntegerLiteral()
        {
	  JJTreeOptions.setInputFileOption(o, v, o.image, new Integer(v.image));
	  jjtThis.initialize(o.image, v.image);
	}
   | v=BooleanLiteral()
        { <caret>
	  JJTreeOptions.setInputFileOption(o, v, o.image,
				     Boolean.valueOf(v.image));
	  jjtThis.initialize(o.image, v.image);
	}
   | v=StringLiteral()
        {
	  String vs = TokenUtils.remove_escapes_and_quotes(v, v.image);
	  JJTreeOptions.setInputFileOption(o, v, o.image, (Object)vs);
	  jjtThis.initialize(o.image, vs);
	}
  ) ";"
}


JAVACODE
void node_descriptor_expression() #NodeDescriptorExpression
{
  Token tok;
  int nesting = 1;
  while (true) {
    tok = getToken(1);
    if (tok.kind == 0) {
      throw new ParseException();
    }
    if (tok.kind == LPAREN) nesting++;
    if (tok.kind == RPAREN) {
      nesting--;
      if (nesting == 0) break;
    }
    tok = getNextToken();
  }
}